/**
 * CHRISTMAS TOWNS — White Christmas domestic destination data
 * For Go Elsewhere / goelsewhere.travel
 *
 * SCHEMA:
 *   name         — Display name
 *   state        — State or Province
 *   country      — US or Canada
 *   region       — Broad region grouping
 *   lat/lng      — Coordinates
 *   nearestAirport — IATA code(s) and drive time
 *   tags         — Descriptive tags for filtering
 *   trainTown    — boolean, has Christmas train service
 *   snowReliability — 'guaranteed' | 'high' | 'moderate'
 *   vibe         — One-line vibe descriptor
 *   notes        — Editorial description
 *   nightlyMid   — Estimated midrange nightly hotel rate (USD)
 */

module.exports.CHRISTMAS_TOWNS = [

  // ─── ROCKY MOUNTAIN / SOUTHWEST ───────────────────────────────────────────

  {
    name: 'Ouray',
    state: 'Colorado',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 38.0228,
    lng: -107.6714,
    nearestAirport: 'MTJ (Montrose, 45 min) or DRO (Durango, 1.5 hrs)',
    tags: ['victorian architecture', 'hot springs', 'ice climbing', 'alpine', 'small town', 'colorado'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Victorian ice-climbing town ringed by 14,000-ft peaks',
    notes: 'The Switzerland of America. Hot springs in the snow, Victorian hotel facades strung with lights, Box Cañon Falls frozen solid. One of the most cinematic Christmas settings in North America.',
    nightlyMid: 180,
  },

  {
    name: 'Silverton',
    state: 'Colorado',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 37.8120,
    lng: -107.6645,
    nearestAirport: 'DRO (Durango, 50 min)',
    tags: ['victorian', 'mining town', 'alpine', 'narrow gauge railroad', 'remote', 'colorado'],
    trainTown: true,
    snowReliability: 'guaranteed',
    vibe: 'Frozen Victorian mining town at 9,318 ft',
    notes: 'End of the line for the Durango & Silverton Narrow Gauge Railroad. The whole town is a National Historic Landmark. At Christmas, snow is guaranteed and crowds are near zero.',
    nightlyMid: 140,
  },

  {
    name: 'Telluride',
    state: 'Colorado',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 37.9375,
    lng: -107.8123,
    nearestAirport: 'TEX (Telluride, on-site) or MTJ (Montrose, 1.5 hrs)',
    tags: ['ski town', 'victorian', 'box canyon', 'alpine', 'upscale', 'colorado'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Upscale ski box-canyon town with Victorian bones',
    notes: 'A box canyon town that goes full Christmas — free gondola to Mountain Village, carolers on Colorado Ave, ski-in/ski-out from a National Historic District. Budget for it.',
    nightlyMid: 350,
  },

  {
    name: 'Steamboat Springs',
    state: 'Colorado',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 40.4850,
    lng: -106.8317,
    nearestAirport: 'HDN (Hayden, 25 min)',
    tags: ['ski town', 'hot springs', 'western', 'family', 'colorado'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Western ski town with hot springs and Champagne Powder',
    notes: 'Less sceney than Aspen or Telluride. Cowboy Christmas vibes — western storefronts, hot springs, and some of the driest powder in Colorado. Locals actually live here.',
    nightlyMid: 220,
  },

  {
    name: 'Taos',
    state: 'New Mexico',
    country: 'US',
    region: 'Southwest',
    lat: 36.4072,
    lng: -105.5730,
    nearestAirport: 'SAF (Santa Fe, 1.5 hrs) or ABQ (Albuquerque, 2.5 hrs)',
    tags: ['adobe', 'pueblo', 'art town', 'farolitos', 'skiing', 'new mexico', 'UNESCO nearby'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Adobe art town with farolito-lit Christmas Eve processions',
    notes: 'Christmas Eve in Taos Pueblo — hundreds of farolitos (paper bag luminarias) lining the ancient adobe walls, bonfires, and traditional dances. Nothing else like it. Taos Ski Valley 30 min away.',
    nightlyMid: 160,
  },

  {
    name: 'Santa Fe',
    state: 'New Mexico',
    country: 'US',
    region: 'Southwest',
    lat: 35.6870,
    lng: -105.9378,
    nearestAirport: 'SAF (Santa Fe, 10 min) or ABQ (Albuquerque, 1 hr)',
    tags: ['adobe', 'art', 'farolitos', 'museums', 'plaza', 'new mexico', 'UNESCO nearby'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'High desert capital city draped in farolitos and snow',
    notes: 'Canyon Road Christmas Eve — thousands of farolitos, bonfires, carolers, and art galleries open late. The plaza goes full Victorian Christmas. Snow is reliable at 7,000 ft.',
    nightlyMid: 200,
  },

  {
    name: 'Flagstaff',
    state: 'Arizona',
    country: 'US',
    region: 'Southwest',
    lat: 35.1983,
    lng: -111.6513,
    nearestAirport: 'FLG (Flagstaff, on-site) or PHX (Phoenix, 2.5 hrs)',
    tags: ['surprise pick', 'snow', 'route 66', 'grand canyon nearby', 'university town', 'arizona'],
    trainTown: true,
    snowReliability: 'high',
    vibe: 'Route 66 mountain town with real snow, Grand Canyon day trip',
    notes: 'Arizona\'s surprise Christmas pick. At 6,900 ft it gets genuine snow while Phoenix bakes. Historic downtown, Route 66 neon, Grand Canyon 90 min away. The Polar Express runs from here.',
    nightlyMid: 130,
  },

  {
    name: 'Jackson Hole',
    state: 'Wyoming',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 43.4799,
    lng: -110.7624,
    nearestAirport: 'JAC (Jackson Hole, on-site)',
    tags: ['ski town', 'grand teton', 'wildlife', 'upscale', 'western', 'wyoming'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Grand Teton gateway with elk herds and antler arches',
    notes: 'Elk antler arches on the town square, National Elk Refuge sleigh rides, Grand Teton peaks lit by alpenglow. World-class skiing. The most photogenic Christmas in the West.',
    nightlyMid: 400,
  },

  {
    name: 'Whitefish',
    state: 'Montana',
    country: 'US',
    region: 'Rocky Mountain',
    lat: 48.4114,
    lng: -114.3359,
    nearestAirport: 'FCA (Kalispell, 20 min)',
    tags: ['ski town', 'glacier nearby', 'small town', 'montana', 'affordable'],
    trainTown: true,
    snowReliability: 'guaranteed',
    vibe: 'Unpretentious Montana ski town near Glacier National Park',
    notes: 'The anti-Aspen. Whitefish Mountain Resort, a charming walkable downtown, and the Empire Builder Amtrak stops here. Glacier National Park is snowed in and spectacular. Affordable by ski town standards.',
    nightlyMid: 160,
  },

  // ─── PACIFIC NORTHWEST ────────────────────────────────────────────────────

  {
    name: 'Leavenworth',
    state: 'Washington',
    country: 'US',
    region: 'Pacific Northwest',
    lat: 47.5962,
    lng: -120.6615,
    nearestAirport: 'SEA (Seattle, 2.5 hrs) or GEG (Spokane, 2 hrs)',
    tags: ['bavarian village', 'christmas lights', 'iconic', 'family', 'washington', 'festivals'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'A full Bavarian village that transforms completely for Christmas',
    notes: 'This one goes all the way. An entire town built to look like a Bavarian alpine village, and at Christmas it becomes something close to surreal — half a million lights, Christmas markets, sleigh rides, carolers in lederhosen. Book October.',
    nightlyMid: 200,
  },

  {
    name: 'Port Townsend',
    state: 'Washington',
    country: 'US',
    region: 'Pacific Northwest',
    lat: 48.1170,
    lng: -122.7604,
    nearestAirport: 'SEA (Seattle, 1.5 hrs + ferry)',
    tags: ['victorian seaport', 'arts', 'ferry town', 'washington', 'pacific northwest'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Victorian seaport with arts scene and Olympic Peninsula access',
    notes: 'The best-preserved Victorian seaport in the Pacific Northwest. Less snow-reliable but the architecture is spectacular and the ferry ride from Seattle is part of the experience.',
    nightlyMid: 150,
  },

  {
    name: 'Ashland',
    state: 'Oregon',
    country: 'US',
    region: 'Pacific Northwest',
    lat: 42.1946,
    lng: -122.7095,
    nearestAirport: 'MFR (Medford, 20 min)',
    tags: ['shakespeare', 'arts', 'small town', 'southern oregon', 'theater'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Shakespeare theater town with Victorian charm and Bear Creek',
    notes: 'Oregon Shakespeare Festival town that pivots beautifully to Christmas. Lithia Park, the creek, the Elizabethan theater district all draped in lights. Less snow than the Rockies but deeply charming.',
    nightlyMid: 140,
  },

  {
    name: 'McCall',
    state: 'Idaho',
    country: 'US',
    region: 'Pacific Northwest',
    lat: 44.9099,
    lng: -116.1002,
    nearestAirport: 'BOI (Boise, 2 hrs)',
    tags: ['lake town', 'ski', 'winter carnival', 'idaho', 'family'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Lake-town ski destination famous for its Winter Carnival ice sculptures',
    notes: 'Payette Lake frozen solid, Brundage Mountain for skiing, and the McCall Winter Carnival ice sculptures are legitimately world-class. Underrated and genuinely affordable.',
    nightlyMid: 130,
  },

  // ─── NEW ENGLAND ─────────────────────────────────────────────────────────

  {
    name: 'Woodstock',
    state: 'Vermont',
    country: 'US',
    region: 'New England',
    lat: 43.6243,
    lng: -72.5218,
    nearestAirport: 'BOS (Boston, 2.5 hrs) or BTV (Burlington, 1.5 hrs)',
    tags: ['covered bridges', 'village green', 'new england', 'vermont', 'iconic christmas'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'The quintessential New England Christmas village',
    notes: 'Covered bridges, a village green with a white church, the Woodstock Inn glowing, and real Vermont snow. This is the postcard. If you want New England Christmas, start here.',
    nightlyMid: 250,
  },

  {
    name: 'Stowe',
    state: 'Vermont',
    country: 'US',
    region: 'New England',
    lat: 44.4654,
    lng: -72.6874,
    nearestAirport: 'BTV (Burlington, 45 min)',
    tags: ['ski town', 'vermont', 'von trapp family', 'new england', 'family'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Vermont\'s premier ski village with Von Trapp Family Lodge',
    notes: 'The Von Trapp Family Lodge is literally here — same family, same land, Austrian chalets in Vermont snow. Mountain Road is lit up, the village is walkable, Mt. Mansfield skiing is excellent.',
    nightlyMid: 280,
  },

  {
    name: 'Manchester',
    state: 'Vermont',
    country: 'US',
    region: 'New England',
    lat: 43.1637,
    lng: -73.0621,
    nearestAirport: 'ALB (Albany, 1 hr) or BDL (Hartford, 2 hrs)',
    tags: ['outlet shopping', 'vermont', 'equinox mountain', 'historic inns', 'new england'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Refined Vermont village with Equinox Mountain and historic inns',
    notes: 'The Equinox Resort anchors a genuinely beautiful village. Orvis flagship is here (for the gifter in the group). Southern Vermont Arts Center, covered bridges, and solid snow.',
    nightlyMid: 200,
  },

  {
    name: 'Lenox',
    state: 'Massachusetts',
    country: 'US',
    region: 'New England',
    lat: 42.3565,
    lng: -73.2832,
    nearestAirport: 'ALB (Albany, 45 min) or BDL (Hartford, 1.5 hrs)',
    tags: ['berkshires', 'gilded age mansions', 'tanglewood', 'arts', 'massachusetts'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Gilded Age Berkshires estate town with arts and architecture',
    notes: 'Shakespeare & Company, the Mount (Edith Wharton\'s estate), and Gilded Age cottages. The Berkshires at Christmas is understated and elegant. Blantyre hotel is special.',
    nightlyMid: 280,
  },

  {
    name: 'Kennebunkport',
    state: 'Maine',
    country: 'US',
    region: 'New England',
    lat: 43.3634,
    lng: -70.4767,
    nearestAirport: 'PWM (Portland, 45 min) or BOS (Boston, 1.5 hrs)',
    tags: ['maine', 'seaport', 'christmas prelude', 'lobster', 'new england', 'coastal'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Maine coastal village famous for its Christmas Prelude festival',
    notes: 'Kennebunkport Christmas Prelude is a 10-day festival — lobster stew tastings, caroling boats in the harbor, tree lightings. The Bush family compound is visible from the water. Deeply New England.',
    nightlyMid: 220,
  },

  {
    name: 'Rockport',
    state: 'Massachusetts',
    country: 'US',
    region: 'New England',
    lat: 42.6559,
    lng: -70.6201,
    nearestAirport: 'BOS (Boston, 1 hr)',
    tags: ['fishing village', 'artists colony', 'cape ann', 'massachusetts', 'coastal'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Cape Ann fishing village and artists colony at the edge of winter',
    notes: 'Motif Number 1 (the most painted building in America) looks best in winter snow with no tourists. Commuter rail from Boston. Small, genuine, and very New England.',
    nightlyMid: 160,
  },

  // ─── MID-ATLANTIC / APPALACHIAN ───────────────────────────────────────────

  {
    name: 'Jim Thorpe',
    state: 'Pennsylvania',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 40.8787,
    lng: -75.7352,
    nearestAirport: 'ABE (Allentown, 45 min) or PHL (Philadelphia, 1.5 hrs)',
    tags: ['victorian', 'lehigh gorge', 'christmas train', 'pennsylvania', 'mountain town', 'coal heritage'],
    trainTown: true,
    snowReliability: 'moderate',
    vibe: 'Victorian coal town in a gorge with the Lehigh Gorge Scenic Railway',
    notes: 'Called the "Switzerland of America" before Ouray stole the nickname. A Victorian town built into a gorge — Opera House, Asa Packer Mansion, cobblestone Broadway St. The Lehigh Gorge Scenic Railway runs Christmas trains. One of the best-kept secrets in PA.',
    nightlyMid: 140,
  },

  {
    name: 'Strasburg',
    state: 'Pennsylvania',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 39.9840,
    lng: -76.1833,
    nearestAirport: 'PHL (Philadelphia, 1.5 hrs) or BWI (Baltimore, 1.5 hrs)',
    tags: ['christmas train', 'amish country', 'railroad museum', 'pennsylvania', 'family', 'lancaster county'],
    trainTown: true,
    snowReliability: 'moderate',
    vibe: 'Amish country train town with America\'s oldest operating railroad',
    notes: 'The Strasburg Rail Road (est. 1832, oldest operating in the US) runs the Santa Claus Special through Lancaster County farmland. Amish buggies in the snow. The Railroad Museum of Pennsylvania is next door. Perfect family Christmas.',
    nightlyMid: 120,
  },

  {
    name: 'New Hope',
    state: 'Pennsylvania',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 40.3615,
    lng: -74.9543,
    nearestAirport: 'PHL (Philadelphia, 45 min) or EWR (Newark, 1 hr)',
    tags: ['delaware river', 'arts', 'christmas train', 'pennsylvania', 'day trip from NYC'],
    trainTown: true,
    snowReliability: 'moderate',
    vibe: 'Delaware River arts town with the New Hope & Ivyland Railroad',
    notes: 'New Hope & Ivyland Railroad runs the North Pole Express. The town sits on the Delaware River across from Lambertville NJ — two walkable arts/antiques towns connected by a bridge. Easy day trip from NYC or Philly.',
    nightlyMid: 160,
  },

  {
    name: 'Gettysburg',
    state: 'Pennsylvania',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 39.8309,
    lng: -77.2311,
    nearestAirport: 'BWI (Baltimore, 1.5 hrs) or PHL (Philadelphia, 2 hrs)',
    tags: ['civil war', 'historic', 'battlefield', 'victorian', 'pennsylvania'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Civil War battlefield town with Victorian storefronts and ghost tours',
    notes: 'The battlefield at Christmas with light snow is quietly extraordinary. The town has excellent Victorian architecture, and the ghost tour industry gives it an unexpected edge. David Wills House where Lincoln finalized the Gettysburg Address.',
    nightlyMid: 130,
  },

  {
    name: 'Harpers Ferry',
    state: 'West Virginia',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 39.3256,
    lng: -77.7297,
    nearestAirport: 'DCA (Washington DC, 1.5 hrs) or BWI (Baltimore, 1.5 hrs)',
    tags: ['john brown', 'rivers confluence', 'historic', 'west virginia', 'civil war', 'day trip from DC'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Historic town at the confluence of two rivers, accessible from DC',
    notes: 'Where the Potomac meets the Shenandoah. Thomas Jefferson called the view "worth a voyage across the Atlantic." The lower town is a National Historic Park — original 19th century stone buildings, almost no modern intrusion. Easy from DC.',
    nightlyMid: 110,
  },

  {
    name: 'Lewisburg',
    state: 'West Virginia',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 37.8023,
    lng: -80.4451,
    nearestAirport: 'LWB (Greenbrier Valley, on-site) or ROA (Roanoke, 1.5 hrs)',
    tags: ['greenbrier nearby', 'historic', 'small town', 'west virginia', 'downtown'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Tiny historic downtown near The Greenbrier resort',
    notes: 'Best small downtown in West Virginia. The Greenbrier resort is 12 miles away (and worth a splurge). Carnegie Hall (the real one, in WV) hosts Christmas concerts. Genuinely undiscovered.',
    nightlyMid: 100,
  },

  {
    name: 'Abingdon',
    state: 'Virginia',
    country: 'US',
    region: 'Mid-Atlantic',
    lat: 36.7096,
    lng: -81.9774,
    nearestAirport: 'TRI (Tri-Cities, 30 min) or ROA (Roanoke, 1.5 hrs)',
    tags: ['barter theatre', 'virginia creeper trail', 'historic', 'virginia', 'appalachian'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Southwest Virginia arts town on the Virginia Creeper Trail',
    notes: 'The Martha Washington Inn (1832) anchors a beautiful historic district. Barter Theatre is one of the oldest professional theaters in the US. Virginia Creeper Trail for winter cycling. Deeply Appalachian and proud of it.',
    nightlyMid: 140,
  },

  // ─── MIDWEST / GREAT LAKES ────────────────────────────────────────────────

  {
    name: 'Galena',
    state: 'Illinois',
    country: 'US',
    region: 'Midwest',
    lat: 42.4167,
    lng: -90.4290,
    nearestAirport: 'DBQ (Dubuque, 30 min) or ORD (Chicago, 2.5 hrs)',
    tags: ['ulysses grant', 'victorian', 'illinois', 'christmas', 'rolling hills', 'day trip from chicago'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Grant\'s Victorian hometown on the Mississippi bluffs, fully Christmas',
    notes: 'Ulysses Grant\'s home town, and it takes Christmas seriously. Main Street is 85% 19th century commercial buildings. The entire town decorates. Jo Daviess County hills look like Vermont with better bourbon.',
    nightlyMid: 150,
  },

  {
    name: 'Bayfield',
    state: 'Wisconsin',
    country: 'US',
    region: 'Midwest',
    lat: 46.8138,
    lng: -90.8196,
    nearestAirport: 'DLH (Duluth, 1.5 hrs)',
    tags: ['apostle islands', 'lake superior', 'ice caves', 'fishing', 'wisconsin', 'remote'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Lake Superior fishing village with Apostle Islands ice caves nearby',
    notes: 'When Lake Superior freezes hard enough, the Apostle Islands sea caves become an ice cave wonderland you walk to on the frozen lake. Bayfield is tiny, beautiful, and the most remote pick on this list. The brave will love it.',
    nightlyMid: 120,
  },

  {
    name: 'Suttons Bay',
    state: 'Michigan',
    country: 'US',
    region: 'Midwest',
    lat: 44.9755,
    lng: -85.6447,
    nearestAirport: 'TVC (Traverse City, 15 min)',
    tags: ['leelanau peninsula', 'wineries', 'lake michigan', 'michigan', 'small town'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Leelanau Peninsula wine country village on Lake Michigan',
    notes: 'A genuinely beautiful small town on the Leelanau Peninsula. Wineries, cherry orchards under snow, Lake Michigan views. Traverse City is 15 min away for more amenities. Michigan\'s answer to Vermont wine country.',
    nightlyMid: 140,
  },

  {
    name: 'Marquette',
    state: 'Michigan',
    country: 'US',
    region: 'Midwest',
    lat: 46.5436,
    lng: -87.3954,
    nearestAirport: 'MQT (Marquette, on-site)',
    tags: ['upper peninsula', 'lake superior', 'iron ore', 'rugged', 'michigan', 'snow guaranteed'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Rugged Upper Peninsula iron port city with guaranteed massive snow',
    notes: 'Marquette averages 140+ inches of snow. It\'s not quaint — it\'s genuinely wild. Lake Superior crashing against iron-ore cliffs in a December blizzard. For the traveler who wants to feel small in winter. Presque Isle Park is stunning.',
    nightlyMid: 110,
  },

  // ─── CANADA ───────────────────────────────────────────────────────────────

  {
    name: 'Quebec City',
    state: 'Quebec',
    country: 'Canada',
    region: 'Canada / East',
    lat: 46.8139,
    lng: -71.2082,
    nearestAirport: 'YQB (Quebec City, 20 min)',
    tags: ['european', 'château frontenac', 'walled city', 'christmas market', 'french', 'UNESCO', 'sleigh rides'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'The most European Christmas in North America — walled city, château, guaranteed snow',
    notes: 'The single best-kept secret on this list for Americans. A UNESCO World Heritage walled city with the Château Frontenac lit up, a German-style Christmas market, horse-drawn sleighs on cobblestones, and snow that never fails. Four hours from Boston. Five from NYC. Almost nobody thinks to go here for Christmas.',
    nightlyMid: 200,
  },

  {
    name: 'Banff',
    state: 'Alberta',
    country: 'Canada',
    region: 'Canada / West',
    lat: 51.1784,
    lng: -115.5708,
    nearestAirport: 'YYC (Calgary, 1.5 hrs)',
    tags: ['canadian rockies', 'fairmont', 'hot springs', 'skiing', 'wildlife', 'Alberta', 'UNESCO'],
    trainTown: false,
    snowReliability: 'guaranteed',
    vibe: 'Canadian Rockies resort town with Fairmont Banff Springs and guaranteed snow',
    notes: 'The Fairmont Banff Springs — a castle in the Rockies — at Christmas is something from a fairy tale. Elk wander the streets. The hot springs are open in -20°C. Lake Louise is 45 min away and frozen solid.',
    nightlyMid: 320,
  },

  {
    name: 'Collingwood',
    state: 'Ontario',
    country: 'Canada',
    region: 'Canada / East',
    lat: 44.5001,
    lng: -80.2170,
    nearestAirport: 'YYZ (Toronto, 1.5 hrs)',
    tags: ['blue mountain', 'ontario', 'georgian bay', 'ski resort', 'day trip from toronto'],
    trainTown: false,
    snowReliability: 'high',
    vibe: 'Georgian Bay ski town, Toronto\'s winter weekend escape',
    notes: 'Blue Mountain resort anchors a genuinely charming waterfront town on Georgian Bay. Collingwood is what Torontonians do at Christmas. For Americans — fly into Toronto, drive an hour and a half.',
    nightlyMid: 180,
  },

  {
    name: 'Niagara-on-the-Lake',
    state: 'Ontario',
    country: 'Canada',
    region: 'Canada / East',
    lat: 43.2553,
    lng: -79.0716,
    nearestAirport: 'YYZ (Toronto, 1.5 hrs) or BUF (Buffalo, 30 min)',
    tags: ['ice wine', 'shaw festival', 'wine country', 'ontario', 'british architecture', 'niagara'],
    trainTown: false,
    snowReliability: 'moderate',
    vibe: 'Loyalist wine town at the mouth of the Niagara River — ice wine harvest season',
    notes: 'Ice wine harvest happens December–January and NOTL is the heart of it. Loyalist-era British architecture draped in Christmas lights, the Shaw Festival theatre, and Niagara Falls 20 min away (and spectacular in winter with ice formation).',
    nightlyMid: 190,
  },

];

/**
 * TRAIN TOWNS (quick filter)
 * Silverton CO · Flagstaff AZ · Whitefish MT · Jim Thorpe PA ·
 * Strasburg PA · New Hope PA
 */

/**
 * BUDGET TIERS
 * Under $130/night: Silverton, Lewisburg, Strasburg, Marquette, Bayfield, McCall
 * $130–$200/night: Ouray, Taos, Leavenworth, Galena, Suttons Bay, Ashland, Woodstock, Quebec City
 * $200+/night: Telluride, Jackson Hole, Stowe, Banff, Lenox, Kennebunkport
 */
