const WORLD_PARKS = [
  { name: "El Yunque National Forest", country: "Puerto Rico (US)", region: "Caribbean", lat: 18.2951, lng: -65.8000, placeId: "ChIJydD9LrOhBIwR0SSym7z2QoM", rating: 4.8, ratingCount: 14934, gateway: "SJU (San Juan, 45 min)", tags: ["rainforest", "waterfall", "hiking", "bioluminescence nearby", "US territory"], notes: "The only tropical rainforest in the US National Forest system. Waterfalls, tower views, bioluminescent bays nearby." },
  { name: "Viñales Valley", country: "Cuba", region: "Caribbean", lat: 22.6052, lng: -83.7256, placeId: "ChIJnYb1uHRRy4gR9ww0pzz3NM8", rating: 4.8, ratingCount: 595, gateway: "HAV (Havana, 3 hrs drive)", tags: ["mogotes", "limestone", "tobacco farms", "horseback riding", "caves", "UNESCO"], notes: "UNESCO limestone mogotes rising from tobacco-farm valleys. Cuba's most otherworldly landscape." },
  { name: "Parque Nacional Los Glaciares", country: "Argentina", region: "South America / Patagonia", lat: -50.3306, lng: -73.2342, placeId: "ChIJVZJRWSiypL0R3dHwpGmtXeY", rating: 4.9, ratingCount: 6354, gateway: "FTE (El Calafate, 1 hr)", tags: ["glacier", "Perito Moreno", "UNESCO", "hiking", "Patagonia", "calving ice"], notes: "Home to Perito Moreno Glacier — one of the few advancing glaciers on Earth. Audible calving from boardwalks." },
  { name: "Torres del Paine National Park", country: "Chile", region: "South America / Patagonia", lat: -50.9423, lng: -73.4068, placeId: "ChIJB6_bgwEbpb0RWM4aRVcmn70", rating: 4.8, ratingCount: 10942, gateway: "PUQ (Punta Arenas, 3.5 hrs drive)", tags: ["granite towers", "W Trek", "glacier", "guanaco", "condor", "hiking", "Patagonia", "UNESCO biosphere"], notes: "The W Trek is one of the world's great multi-day hikes. Granite towers, turquoise lakes, Grey Glacier." },
  { name: "Salar de Uyuni", country: "Bolivia", region: "South America / Andes", lat: -20.1338, lng: -67.4891, placeId: "ChIJ14vhJbOEVZERtniCFToY5Aw", rating: 4.8, ratingCount: 3056, gateway: "UYU (Uyuni, on-site) via LPB (La Paz)", tags: ["salt flat", "mirror effect", "cactus islands", "flamingos", "altitude", "surreal"], notes: "World's largest salt flat. Wet season mirror effect reflects the entire sky. Altitude 3,656m — acclimatize first." },
  { name: "Chapada Diamantina National Park", country: "Brazil", region: "South America / Brazil", lat: -12.7927, lng: -41.4123, placeId: "ChIJvxVjS7whQgcRvbnUHVNZb1s", rating: 4.9, ratingCount: 10836, gateway: "SSA (Salvador, 4 hrs drive) or LEC (Lençóis, airstrip)", tags: ["table mountains", "waterfalls", "caves", "crystal rivers", "multi-day trek", "Bahia"], notes: "Brazil's secret: table-top mountains, crystal-blue rivers, caves, waterfalls. Base in Lençóis. 4+ days minimum." },
  { name: "Parque Nacional Galápagos", country: "Ecuador", region: "South America / Pacific", lat: -0.6144, lng: -90.3451, placeId: "ChIJQ8p4MDxfqpoRW7ZiDEGJ3Io", rating: 4.8, ratingCount: 3554, gateway: "GYE or UIO (Ecuador mainland) → GPS (Baltra) or SCY (San Cristóbal)", tags: ["Darwin", "endemic species", "marine iguana", "giant tortoise", "UNESCO", "snorkeling", "wildlife"], notes: "Darwin's laboratory. 97% of reptile species found nowhere else. Marine iguanas, flightless cormorants, Galápagos penguins." },
  { name: "Banff National Park", country: "Canada", region: "North America / Canada", lat: 51.4968, lng: -115.9281, placeId: "ChIJlZGSjCtmd1MR5tfKrGjincA", rating: 4.8, ratingCount: 29822, gateway: "YYC (Calgary, 1.5 hrs drive)", tags: ["Canadian Rockies", "turquoise lakes", "Moraine Lake", "Lake Louise", "Icefields Parkway", "wildlife", "skiing"], notes: "Turquoise glacier-fed lakes (Moraine, Louise), Rocky Mountain peaks, Columbia Icefield. Canada's crown jewel." },
  { name: "Plitvice Lakes National Park", country: "Croatia", region: "Europe / Balkans", lat: 44.8654, lng: 15.5820, placeId: "ChIJPQ_Z_mxeYUcRcF6aN_iPGgU", rating: 4.8, ratingCount: 124484, gateway: "ZAG (Zagreb, 2 hrs) or SPU (Split, 2.5 hrs)", tags: ["turquoise lakes", "waterfalls", "boardwalks", "UNESCO", "hiking", "Croatia"], notes: "16 terraced turquoise lakes connected by waterfalls and wooden boardwalks. Go in winter for zero crowds and frozen magic." },
  { name: "Dolomiti Bellunesi National Park", country: "Italy", region: "Europe / Alps", lat: 46.1699, lng: 12.0366, placeId: "ChIJX0Pi4gf8eEcRcsr107cGc1o", rating: 4.7, ratingCount: 3031, gateway: "VCE (Venice, 1.5 hrs) or BLQ (Bologna, 2 hrs)", tags: ["Dolomites", "limestone spires", "UNESCO", "hiking", "no crowds", "Italian Alps"], notes: "Least-visited corner of the Dolomites UNESCO site. Primordial limestone, isolated villages, no mass tourism." },
  { name: "Simien Mountains National Park", country: "Ethiopia", region: "Africa / East Africa", lat: 13.2027, lng: 37.8876, placeId: "ChIJnfgWbdTBaRYRLWISc9-EAnc", rating: 4.5, ratingCount: 294, gateway: "GDQ (Gondar, 2 hrs drive) via ADD (Addis Ababa)", tags: ["gelada baboon", "Ethiopian wolf", "escarpment", "trekking", "UNESCO", "highlands", "Ras Dashen"], notes: "Dramatic highland escarpments, gelada baboons at cliff edges at sunset. Ras Dashen is Africa's 4th highest peak." },
  { name: "Erta Ale / Danakil Depression", country: "Ethiopia", region: "Africa / East Africa", lat: 13.6069, lng: 40.6617, placeId: "ChIJa7-GnkJgFBYRGLm54re0yww", rating: 4.6, ratingCount: 336, gateway: "MQX (Mekele, 6+ hrs 4WD) via ADD (Addis Ababa)", tags: ["lava lake", "active volcano", "sulfur springs", "below sea level", "extreme", "Afar", "most alien landscape"], notes: "Most alien landscape on Earth — 116m below sea level, neon sulfur springs, active lava lake. Hottest inhabited place on the planet." },
  { name: "Namib-Naukluft National Park", country: "Namibia", region: "Africa / Southern Africa", lat: -23.0833, lng: 15.1667, placeId: "ChIJVWbMOIBtchwRDhKhKfVF2_Y", rating: 4.6, ratingCount: 2196, gateway: "WDH (Windhoek, 4 hrs drive) or self-drive", tags: ["sand dunes", "Sossusvlei", "Deadvlei", "world's oldest desert", "photography", "Dune 45", "orange dunes"], notes: "World's oldest desert. Sossusvlei's burnt-orange dunes at sunrise, Deadvlei's ancient dead trees on white clay. Photography icon." },
  { name: "Virunga National Park", country: "Democratic Republic of Congo", region: "Africa / Central Africa", lat: -0.0502, lng: 29.5143, placeId: "ChIJ0-rNko3FYBcRPzjbi0xEgoU", rating: 4.4, ratingCount: 525, gateway: "GOM (Goma, DRC) or KGL (Kigali, Rwanda, 3 hrs)", tags: ["mountain gorilla", "Nyiragongo volcano", "lava lake", "Africa's oldest park", "trekking", "extreme"], notes: "Africa's oldest park. Mountain gorilla trekking and Nyiragongo lava lake summit. Most profound wildlife encounter on earth. Check current security advisories." },
  { name: "Sagarmatha National Park", country: "Nepal", region: "Asia / Himalayas", lat: 27.9324, lng: 86.7014, placeId: "ChIJW_9Y6LlU6DkRvkeHfWBmlKc", rating: 4.6, ratingCount: 2205, gateway: "KTM (Kathmandu) → LUA (Lukla, 30 min flight)", tags: ["Everest", "EBC trek", "Himalaya", "UNESCO", "Sherpa culture", "glacier", "highest peaks"], notes: "Three of the six tallest mountains including Everest. EBC trek through Sherpa villages, glacial rivers, swing bridges." },
  { name: "Jiuzhai Valley National Park", country: "China", region: "Asia / China", lat: 33.2600, lng: 103.9186, placeId: "ChIJKWccnva99zYRxgz2tcjo_ck", rating: 4.7, ratingCount: 1096, gateway: "JZH (Jiuzhaigou, 40 min) or CTU (Chengdu, high-speed rail 2 hrs + bus)", tags: ["turquoise lakes", "multi-colored pools", "waterfalls", "Tibetan valley", "UNESCO", "fairy land", "boardwalk"], notes: "Tiered turquoise lakes and multi-colored pools in a Tibetan valley. Looks like a painting. Book ahead — daily visitor cap." },
  { name: "Zhangjiajie National Forest Park", country: "China", region: "Asia / China", lat: 29.3153, lng: 110.4348, placeId: "ChIJoaxDGsqvmzYRbwukZex5gKE", rating: 4.7, ratingCount: 1118, gateway: "DYG (Zhangjiajie, 1 hr)", tags: ["sandstone pillars", "Avatar", "Hallelujah Mountains", "glass bridge", "cable car", "Hunan", "China"], notes: "The floating sandstone pillars that inspired Avatar's Hallelujah Mountains. Glass-bottomed bridges, vertiginous cable cars. 2 full days minimum." },
  { name: "Kawah Ijen Volcano", country: "Indonesia", region: "Asia / Southeast Asia", lat: -8.0742, lng: 114.2232, placeId: "ChIJX9sVyVBO0S0Rcvyc3gHwCcM", rating: 4.8, ratingCount: 577, gateway: "BWX (Banyuwangi, 1.5 hrs drive) via SUB (Surabaya)", tags: ["blue fire", "active volcano", "acid lake", "sulfur", "night hike", "Java", "Indonesia"], notes: "World's only blue fire volcano — electric-blue sulfuric flames visible only at night. Hike starts at 2am. Gas mask required." },
  { name: "Milford Sound / Piopiotahi", country: "New Zealand", region: "Oceania / New Zealand", lat: -44.6414, lng: 167.8974, placeId: "ChIJ4UlLuk3g1akRAN5kq4bvACo", rating: 4.8, ratingCount: 2637, gateway: "ZQN (Queenstown, 4 hrs drive) or direct charter flight", tags: ["fiord", "waterfalls", "dolphins", "seals", "Fiordland", "UNESCO", "cruise", "New Zealand"], notes: "Sheer cliffs, cascading waterfalls, dolphins, seals. Drive through Homer Tunnel — the road itself is legendary." },
  { name: "Waitomo Glowworm Caves", country: "New Zealand", region: "Oceania / New Zealand", lat: -38.2607, lng: 175.1036, placeId: "ChIJfVTj8363bG0R8p8w_eGxLJI", rating: 4.5, ratingCount: 13024, gateway: "AKL (Auckland, 2 hrs drive) or HLZ (Hamilton, 1 hr)", tags: ["glowworms", "bioluminescent", "caves", "boat ride", "North Island", "unique", "New Zealand"], notes: "Thousands of bioluminescent Arachnocampa luminosa create a living starfield on cave ceilings. Silent boat ride underneath." },
];

module.exports = { WORLD_PARKS };
